version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
endGatewayCulling = true
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
customportalapi = true
naturalist = true
farmersdelight = true
bountiful = true
betterarcheology = true
travelersbackpack = true
alloy_forgery = true
immersive_weathering = true
adventurez = true
deeperdarker = true
betternether = true
endrem = true
bosses_of_mass_destruction = true
mythicmounts = true
snowrealmagic = true
betterend = true
villagersplus = true
advancednetherite = true
comforts = true
fwaystones = true
minecraft = true
animal_feeding_trough = true
gobber2 = true
